
Bump actions/github-script from 6 to 9 #1
All jobs
Run details
Triggered via pull request 1 minute ago
@dependabotdependabot[bot]
opened
#3
dependabot/github_actions/actions/github-script-9
Status
Failure
Total duration
8s
Artifacts
–


Annotations
1 error and 1 notice
welcome
Unhandled error: HttpError: Resource not accessible by integration - https://docs.github.com/rest/issues/comments#create-an-issue-comment
welcome
"The ubuntu-latest label will migrate to Ubuntu 26 beginning October 19, 2026. For more information, see https://github.com/actions/runner-images/issues/14748"
